//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.27 at 05:44:14 PM IST 
//


package cimb3rdparty.billpaymentws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BillDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BillDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://CIMB3rdParty/BillPaymentWS}BillCurrency" minOccurs="0"/>
 *         &lt;element ref="{http://CIMB3rdParty/BillPaymentWS}BillCode" minOccurs="0"/>
 *         &lt;element ref="{http://CIMB3rdParty/BillPaymentWS}BillAmount" minOccurs="0"/>
 *         &lt;element ref="{http://CIMB3rdParty/BillPaymentWS}BillReference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BillDetail", propOrder = {
    "billCurrency",
    "billCode",
    "billAmount",
    "billReference"
})
public class BillDetail {

    @XmlElement(name = "BillCurrency")
    protected String billCurrency;
    @XmlElement(name = "BillCode")
    protected String billCode;
    @XmlElement(name = "BillAmount")
    protected Integer billAmount;
    @XmlElement(name = "BillReference")
    protected String billReference;

    /**
     * Gets the value of the billCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCurrency() {
        return billCurrency;
    }

    /**
     * Sets the value of the billCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCurrency(String value) {
        this.billCurrency = value;
    }

    /**
     * Gets the value of the billCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillCode() {
        return billCode;
    }

    /**
     * Sets the value of the billCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillCode(String value) {
        this.billCode = value;
    }

    /**
     * Gets the value of the billAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBillAmount() {
        return billAmount;
    }

    /**
     * Sets the value of the billAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBillAmount(Integer value) {
        this.billAmount = value;
    }

    /**
     * Gets the value of the billReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillReference() {
        return billReference;
    }

    /**
     * Sets the value of the billReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillReference(String value) {
        this.billReference = value;
    }

}
