//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 10:12:35 PM IST 
//


package cimb3rdparty.billpaymentws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CIMB3rdParty_PaymentRs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIMB3rdParty_PaymentRs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://CIMB3rdParty/BillPaymentWS}PaymentRs" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIMB3rdParty_PaymentRs", propOrder = {
    "paymentRs"
})
public class CIMB3RdPartyPaymentRs {

    @XmlElement(name = "PaymentRs")
    protected PaymentRs paymentRs;

    /**
     * Gets the value of the paymentRs property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentRs }
     *     
     */
    public PaymentRs getPaymentRs() {
        return paymentRs;
    }

    /**
     * Sets the value of the paymentRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentRs }
     *     
     */
    public void setPaymentRs(PaymentRs value) {
        this.paymentRs = value;
    }

}
