//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.27 at 05:44:14 PM IST 
//


package cimb3rdparty.billpaymentws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CIMB3rdParty_InquiryRs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CIMB3rdParty_InquiryRs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://CIMB3rdParty/BillPaymentWS}InquiryRs" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CIMB3rdParty_InquiryRs", propOrder = {
    "inquiryRs"
})
public class CIMB3RdPartyInquiryRs {

    @XmlElement(name = "InquiryRs")
    protected InquiryRs inquiryRs;

    /**
     * Gets the value of the inquiryRs property.
     * 
     * @return
     *     possible object is
     *     {@link InquiryRs }
     *     
     */
    public InquiryRs getInquiryRs() {
        return inquiryRs;
    }

    /**
     * Sets the value of the inquiryRs property.
     * 
     * @param value
     *     allowed object is
     *     {@link InquiryRs }
     *     
     */
    public void setInquiryRs(InquiryRs value) {
        this.inquiryRs = value;
    }

}
