//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.27 at 05:44:14 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://CIMB3rdParty/BillPaymentWS", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package cimb3rdparty.billpaymentws;
